#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-Lahman
Version  : 8.0.1
Release  : 30
URL      : https://cran.r-project.org/src/contrib/Lahman_8.0-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/Lahman_8.0-1.tar.gz
Summary  : Sean 'Lahman' Baseball Database
Group    : Development/Tools
License  : GPL-2.0
Requires: R-car
Requires: R-dplyr
Requires: R-reshape2
BuildRequires : R-car
BuildRequires : R-dplyr
BuildRequires : R-reshape2
BuildRequires : buildreq-R

%description
a set of R data.frames. It uses the data on pitching, hitting and fielding
    performance and other tables from 1871 through 2019, as recorded in the 2020
    version of the database. Documentation examples show how many baseball
    questions can be investigated.

%prep
%setup -q -c -n Lahman
cd %{_builddir}/Lahman

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1611275747

%install
export SOURCE_DATE_EPOCH=1611275747
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Lahman
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Lahman
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Lahman
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc Lahman || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Lahman/DESC-temp-change-maintainer.txt
/usr/lib64/R/library/Lahman/DESCRIPTION
/usr/lib64/R/library/Lahman/INDEX
/usr/lib64/R/library/Lahman/Meta/Rd.rds
/usr/lib64/R/library/Lahman/Meta/data.rds
/usr/lib64/R/library/Lahman/Meta/demo.rds
/usr/lib64/R/library/Lahman/Meta/features.rds
/usr/lib64/R/library/Lahman/Meta/hsearch.rds
/usr/lib64/R/library/Lahman/Meta/links.rds
/usr/lib64/R/library/Lahman/Meta/nsInfo.rds
/usr/lib64/R/library/Lahman/Meta/package.rds
/usr/lib64/R/library/Lahman/Meta/vignette.rds
/usr/lib64/R/library/Lahman/NAMESPACE
/usr/lib64/R/library/Lahman/NEWS
/usr/lib64/R/library/Lahman/R/Lahman
/usr/lib64/R/library/Lahman/R/Lahman.rdb
/usr/lib64/R/library/Lahman/R/Lahman.rdx
/usr/lib64/R/library/Lahman/data/Rdata.rdb
/usr/lib64/R/library/Lahman/data/Rdata.rds
/usr/lib64/R/library/Lahman/data/Rdata.rdx
/usr/lib64/R/library/Lahman/data/datalist
/usr/lib64/R/library/Lahman/demo/batting-summstats.R
/usr/lib64/R/library/Lahman/demo/lahman-dplyr.R
/usr/lib64/R/library/Lahman/doc/hits-by-type.R
/usr/lib64/R/library/Lahman/doc/hits-by-type.Rmd
/usr/lib64/R/library/Lahman/doc/hits-by-type.html
/usr/lib64/R/library/Lahman/doc/index.html
/usr/lib64/R/library/Lahman/doc/payroll.R
/usr/lib64/R/library/Lahman/doc/payroll.Rmd
/usr/lib64/R/library/Lahman/doc/payroll.html
/usr/lib64/R/library/Lahman/doc/run-scoring-trends.R
/usr/lib64/R/library/Lahman/doc/run-scoring-trends.Rmd
/usr/lib64/R/library/Lahman/doc/run-scoring-trends.html
/usr/lib64/R/library/Lahman/doc/strikeoutsandhr.R
/usr/lib64/R/library/Lahman/doc/strikeoutsandhr.Rmd
/usr/lib64/R/library/Lahman/doc/strikeoutsandhr.html
/usr/lib64/R/library/Lahman/doc/vignette-intro.Rmd
/usr/lib64/R/library/Lahman/doc/vignette-intro.html
/usr/lib64/R/library/Lahman/help/AnIndex
/usr/lib64/R/library/Lahman/help/Lahman.rdb
/usr/lib64/R/library/Lahman/help/Lahman.rdx
/usr/lib64/R/library/Lahman/help/aliases.rds
/usr/lib64/R/library/Lahman/help/paths.rds
/usr/lib64/R/library/Lahman/html/00Index.html
/usr/lib64/R/library/Lahman/html/R.css
/usr/lib64/R/library/Lahman/scripts/LahmanData.R
/usr/lib64/R/library/Lahman/scripts/check_revdep.R
/usr/lib64/R/library/Lahman/scripts/compress-data.R
/usr/lib64/R/library/Lahman/scripts/lahman-compare.R
/usr/lib64/R/library/Lahman/scripts/readLahman.R
